MEM_ARGS: "-Xms128m -Xmx128m -Xss256k -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -XX:MaxDirectMemorySize=10m -XX:ReservedCodeCacheSize=32M -XX:CompressedClassSpaceSize=32M -XX:MinMetaspaceExpansion=1M -XX:MaxMetaspaceExpansion=8M -XX:CodeCacheExpansionSize=256k -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90"
MEMORY_LIMIT: "435Mi"
CPU_REQUEST: "100m"
CPU_LIMIT: "2"
REPLICAS: 2
XNIO_IO_THREAD: 14
XNIO_WORK_THREAD: 112
HPA_ENABLED: true
HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT: 75
HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS: 60
HPA_SCALING_UP_PODS_PERIOD_SECONDS: 60
HPA_SCALING_UP_PODS_VALUE: 1
HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS: 300
HPA_SCALING_DOWN_PODS_PERIOD_SECONDS: 60
HPA_SCALING_DOWN_PODS_VALUE: 1
HPA_MIN_REPLICAS: 2
HPA_MAX_REPLICAS: 5
HPA_SCALING_UP_SELECT_POLICY: Max
HPA_SCALING_DOWN_SELECT_POLICY: Max
HPA_SCALING_UP_PERCENT_PERIOD_SECONDS: -1
HPA_SCALING_DOWN_PERCENT_PERIOD_SECONDS: -1