{
 "title": "Java Process Details",
 "tags": [
  "java",
  "Prometheus"
 ],
 "time": { "from": "now-30m", "to": "now-5s" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(jvm_memory_used_bytes{namespace='$namespace',}, container)"
   },
   {
    "name": "pod_name",
    "label": "Pod name",
    "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", container=\"$service_name\"}, pod)"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Java Process Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health $pod_name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "repeat": "pod_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{exported_namespace=\"$namespace\", exported_pod=\"$pod_name\", exported_pod!~\".*deploy\", container=\"$service_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime: $pod_name",
   "type": "singlestat",
   "description": "Shows selected service uptime",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "repeat": "pod_name",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Threads: $pod_name",
   "type": "singlestat",
   "description": "Shows amount of threads active in the selected service",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"$namespace\", pod=\"$pod_name\", container=\"$service_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Opened FD $pod_name",
   "type": "singlestat",
   "description": "Number of currently opened file descriptors",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_files_open_files{namespace=\"$namespace\", pod=\"$pod_name\", container=\"$service_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage: $pod_name",
   "type": "graph",
   "description": "Summary of CPU usage by process $service_name.\n\nThe red line shows limit of CPUs usage for the process.\n\nThe values is indicated in Millicores. It is a special Kubernates metric means CPU core split into 1000 units.\n\nData comes from cloud monitoring, not always available",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "usage",
     "expr": "rate(container_cpu_usage_seconds_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "usage",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "limit",
     "expr": "kube_pod_container_resource_limits_cpu_cores{container=\"$service_name\", exported_namespace=\"$namespace\", exported_pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "limit",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "request",
     "expr": "kube_pod_container_resource_requests_cpu_cores{container=\"$service_name\", exported_namespace=\"$namespace\", exported_pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "request",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    }
   ]
  },
  {
   "title": "Commited Memory $pod_name",
   "type": "graph",
   "description": "The amount of used memory (Stack value)",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 5 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Limit",
     "expr": "kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\", exported_pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Limits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Limit",
     "expr": "kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\", exported_pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Request",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Usage",
     "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heap: $tag_id",
     "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", pod=\"$pod_name\"} ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "NonHeap: {{id}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Non Heap: $tag_id",
     "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Heap: {{id}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Files $pod_name",
   "type": "graph",
   "description": "The open file descriptor count (average for current time interval)",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 5 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "open",
     "expr": "avg(process_files_open_files{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage: Eden Space $pod_name",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 28 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Eden Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Eden Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Eden Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Usage:  Tenured Gen $pod_name",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 28 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Tenured Gen\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Tenured Gen\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Tenured Gen\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Usage: Survivor Space $pod_name",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 28 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Survivor Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Survivor Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Survivor Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Usage: Eden Space $pod_name",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Eden Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Eden Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Eden Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Usage:  Tenured Gen $pod_name",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Tenured Gen\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Tenured Gen\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Tenured Gen\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Heap Usage: Survivor Space $pod_name",
     "type": "graph",
     "description": "The amount of used memory in heap area multiplied by different ids",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Survivor Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Survivor Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"heap\", id=\"Survivor Space\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non Heap: Code Cache $pod_name",
     "type": "graph",
     "description": "The amount of used memory in non heap area multiplied by different ids",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"Code Cache\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"Code Cache\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"Code Cache\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Non Heap: Metaspace $pod_name",
     "type": "graph",
     "description": "The amount of used memory in non heap area multiplied by different ids",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"Metaspace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "committed",
       "expr": "jvm_memory_committed_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"Metaspace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "committed",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "allocated",
       "expr": "jvm_memory_max_bytes{container=\"$service_name\", namespace=\"$namespace\", area=\"nonheap\", id=\"Metaspace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "allocated",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Byte buffers: Direct $pod_name",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool (Off-heap buffers from allocateDirect())",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_buffer_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"direct\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "capacity",
       "expr": "jvm_buffer_total_capacity_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"direct\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "capacity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Byte buffers: Mapped $pod_name",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool (Off-heap buffers from allocateDirect())",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "expr": "jvm_buffer_memory_used_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"mapped\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "capacity",
       "expr": "jvm_buffer_total_capacity_bytes{container=\"$service_name\", namespace=\"$namespace\", id=\"mapped\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "capacity",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC: Pauses $pod_name",
     "type": "graph",
     "description": "Time spent for minor and major GC per second",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "s", "label": "pauses/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_cause: $tag_action",
       "expr": "rate(jvm_gc_pause_seconds_sum{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{cause}}: {{action}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC: Allocations $pod_name",
     "type": "graph",
     "description": "Increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Allocations",
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Allocations",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC: Pauses $pod_name",
     "type": "graph",
     "description": "Time spent for minor and major GC per second",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "s", "label": "pauses/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_cause: $tag_action",
       "expr": "rate(jvm_gc_pause_seconds_sum{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{cause}}: {{action}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC: Allocations $pod_name",
     "type": "graph",
     "description": "Increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Allocations",
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Allocations",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads $pod_name",
     "type": "graph",
     "description": "Shows information about Java threads",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "current",
       "expr": "jvm_threads_live_threads{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "current",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "daemon",
       "expr": "jvm_threads_daemon_threads{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "daemon",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "peak",
       "expr": "jvm_threads_peak_threads{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "peak",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Threads: State $pod_name",
     "type": "graph",
     "description": "Shows information about Java threads",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "runnable",
       "expr": "jvm_threads_states_threads{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{state}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JDBC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL JDBC Connections $pod_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Active",
       "expr": "jdbc_connections_active{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Active",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max",
       "expr": "jdbc_connections_max{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Idle",
       "expr": "jdbc_connections_idle{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Idle",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hickari Pool: Connections $pod_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Active",
       "expr": "hikaricp_connections_active{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"} OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Active",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Idle",
       "expr": "hikaricp_connections_idle{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Idle",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max",
       "expr": "hikaricp_connections_max{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Pending",
       "expr": "hikaricp_connections_pending{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Pending",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Hickari Pool: Usage $pod_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "Usage",
       "expr": "rate(hikaricp_connections_usage_seconds_sum{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Usage",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Count",
       "expr": "increase(hikaricp_connections_usage_seconds_count{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Count",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log events $pod_name",
     "type": "graph",
     "description": "Logback logging event stream",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "event/sec" }
     ],
     "targets": [
      {
       "alias": "trace",
       "expr": "rate(logback_events_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{level}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Log events $pod_name",
     "type": "graph",
     "description": "Logback logging event stream",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "event/sec" }
     ],
     "targets": [
      {
       "alias": "trace",
       "expr": "rate(logback_events_total{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{level}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoint Statistics. Code: 2xx $pod_name",
     "type": "graph",
     "description": "Shows amount of successful requests to different URLs per second",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"2..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Statistics. Code: 2xx $pod_name",
     "type": "graph",
     "description": "Shows amount of successful requests to different URLs per second",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"2..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Timings. Code 2xx $pod_name",
     "type": "graph",
     "description": "Shows maximum time of requests execution to service endpoints",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "increase(http_server_requests_seconds_max{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Timings. Code 2xx $pod_name",
     "type": "graph",
     "description": "Shows maximum time of requests execution to service endpoints",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "increase(http_server_requests_seconds_max{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoint Statistics. Code: 4xx $pod_name",
     "type": "graph",
     "description": "Shows amount of requests to different URLs per second with code 4xx",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"4..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Statistics. Code: 4xx $pod_name",
     "type": "graph",
     "description": "Shows amount of requests to different URLs per second with code 4xx",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"4..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Statistics. Code: 5xx $pod_name",
     "type": "graph",
     "description": "Shows amount of requests to different URLs per second with code 5xx",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"5..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Statistics. Code: 5xx $pod_name",
     "type": "graph",
     "description": "Shows amount of requests to different URLs per second with code 5xx",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_uri",
       "expr": "rate(http_server_requests_seconds_count{container=\"$service_name\", namespace=\"$namespace\", status=~\"5..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{uri}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}