---
apiVersion: v1
kind: Secret
metadata:
  name: dbaas-config-server-credential-secret
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/part-of: 'Cloud-Core'
    app.kubernetes.io/managed-by: 'saasDeployer'
    deployment.qubership.org/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
stringData:
  username: '{{ .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME | default "cluster-dba" }}'
  password: '{{ .Values.DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD | default "password" }}'
